apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-web-app.frontend.fullname" . }}-html
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  index.html: |
{{ .Values.frontendHTML | indent 4 }}